### ISSUE TITLE
ToDo-Liste (für Bots)

### ISSUE THREAD

**Issue by JBugelLOL** [JBugelLOL/Vibecord#2]
- [x] × ModMail
- [ ] × Security/Captcha
- [ ] × Musik

(Diese Liste wird regelmäßig aktuell gehalten)

**Comment by JBugelLOL** [comment]
**ToDo-Channels**

- [ ] × Informations-Channel
- [x] × Einführungs-Channel
- [x] × TempVoice-Info-Channel
- [ ] × Rollenzuweisung-Channel incl. Rollen
- [ ] × Chat-Redesign

(**Diese Liste wird regelmäßig aktuell gehalten und geupdatet!**)

**Comment by JBugelLOL** [comment]
> **ToDo-Channels**
> 
> - [ ] × Informations-Channel
> - [x] × Einführungs-Channel
> - [x] × TempVoice-Info-Channel
> - [ ] × Rollenzuweisung-Channel incl. Rollen
> - [x] × Chat-Redesign
> 
> (**Diese Liste wird regelmäßig aktuell gehalten und geupdatet!**)

- [x] Chat-Redesign [siehe hier](https://media.discordapp.net/attachments/948818141708943380/960781305124106260/Screenshot_20220405-080104_Discord-Beta.jpg)
